 - name: Install httpd
   hosts: web
   become: true
   tasks: 
     
     - name: install httpd
       ansible.builtin.yum:
         name: httpd
         state: installed
         
     - name: Start service httpd, if not started
       ansible.builtin.service:
         name: httpd
         state: started
#         enabled: yes
