 - name: remove multi packages
   hosts: web
   become: true
   tasks: 
#     - name: Remove the latest version of screen, httpd and tree
#       ansible.builtin.package:
#         name:
#           - screen
#           - tree
#           - httpd
#         state: absent
      - name: Remove a list of packages
        ansible.builtin.yum:
          name:
          - httpd
          - tree
          - screen
          state: absent
      - name: Remove dependencies that are no longer required and purge their configuration files
        ansible.builtin.yum:
          autoremove : yes
          update_cache: yes
        #  cache_clean: yes
