- name: Create file on bo nodes of web servers group
  hosts: web
  become: true 
  tasks:

   - name: Create file
     ansible.builtin.file:
       path: /home/ansadmin/createfiletest1.txt
       state: touch 
